import { User, ActivityLog, BehaviorReport, Startup } from './types';

export const initialStartups: Startup[] = [
  {
    "id": "s1",
    "name": "Kroombox",
    "description": ""
  },
  {
    "id": "s2",
    "name": "JagoAI",
    "description": ""
  },
  {
    "id": "s3",
    "name": "Uniinside",
    "description": ""
  },
  {
    "id": "s4",
    "name": "Ngolab",
    "description": ""
  },
  {
    "id": "s5",
    "name": "Sorgummi",
    "description": ""
  }
];

export const initialUsers: User[] = [
  {
    id: 'u1',
    name: 'Pembimbing Lapangan (HR)',
    email: 'hr.kolab@gmail.com',
    password: 'kolabcreativehub',
    role: 'field',
    score: 0,
    attendanceCount: 0,
    totalDays: 0,
  },
  {
    id: 'acad_0',
    name: 'Robbi Hendriyanto (Pembimbing Akademik)',
    email: 'robbi.hendriyanto@kolab.com',
    password: 'dosenakademik@26',
    role: 'academic',
    score: 0,
    attendanceCount: 0,
    totalDays: 0,
    lecturerCode: 'RHN',
    advisedStartups: [initialStartups[0].name],
    status: 'active'
  },
  {
    id: 'acad_1',
    name: 'Heru Nugroho (Pembimbing Akademik)',
    email: 'heru.nugroho@kolab.com',
    password: 'dosenakademik@26',
    role: 'academic',
    score: 0,
    attendanceCount: 0,
    totalDays: 0,
    lecturerCode: 'HRO',
    advisedStartups: [initialStartups[1].name],
    status: 'active'
  },
  {
    id: 'acad_2',
    name: 'Muhammad Yusuf Ramadhan (Pembimbing Akademik)',
    email: 'muhammad.yusuf.ramadhan@kolab.com',
    password: 'dosenakademik@26',
    role: 'academic',
    score: 0,
    attendanceCount: 0,
    totalDays: 0,
    lecturerCode: 'MFH',
    advisedStartups: [initialStartups[2].name],
    status: 'active'
  },
  {
    id: 'acad_3',
    name: 'Muhammad Nugraha (Pembimbing Akademik)',
    email: 'muhammad.nugraha@kolab.com',
    password: 'dosenakademik@26',
    role: 'academic',
    score: 0,
    attendanceCount: 0,
    totalDays: 0,
    lecturerCode: 'MHN',
    advisedStartups: [initialStartups[3].name],
    status: 'active'
  },
  {
    id: 'intern_0',
    name: 'Muhammad Hafizh Raharja',
    email: 'muhammad0@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607124000055',
    startup: initialStartups[0].name,
    status: 'active'
  },
  {
    id: 'intern_1',
    name: 'Salman Ridhwan Qomarudin',
    email: 'salman1@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607012430004',
    startup: initialStartups[1].name,
    status: 'active'
  },
  {
    id: 'intern_2',
    name: 'AFRISYA DWIKY MAULIDDINKA',
    email: 'afrisya2@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607012400072',
    startup: initialStartups[2].name,
    status: 'active'
  },
  {
    id: 'intern_3',
    name: 'Shafnat Fuaini Ramadhan',
    email: 'shafnat3@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607012400075',
    startup: initialStartups[3].name,
    status: 'active'
  },
  {
    id: 'intern_4',
    name: 'Inaya Faridah',
    email: 'inaya4@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607012430016',
    startup: initialStartups[4].name,
    status: 'active'
  },
  {
    id: 'intern_5',
    name: 'Fazrina Esa Putri Permana',
    email: 'fazrina5@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607012400047',
    startup: initialStartups[0].name,
    status: 'active'
  },
  {
    id: 'intern_6',
    name: 'Dalfa Munawwarotul Mahmudah',
    email: 'dalfa6@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607012430008',
    startup: initialStartups[1].name,
    status: 'active'
  },
  {
    id: 'intern_7',
    name: 'Rafi Abi Assyarif',
    email: 'rafi7@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607012400069',
    startup: initialStartups[2].name,
    status: 'active'
  },
  {
    id: 'intern_8',
    name: 'Amelia Waruwu',
    email: 'amelia8@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607012400052',
    startup: initialStartups[3].name,
    status: 'active'
  },
  {
    id: 'intern_9',
    name: 'Andi Ahmad Nurmadani',
    email: 'andi9@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607012400044',
    startup: initialStartups[4].name,
    status: 'active'
  },
  {
    id: 'intern_10',
    name: 'Muhammad Faisal Rahman',
    email: 'muhammad10@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607012400003',
    startup: initialStartups[0].name,
    status: 'active'
  },
  {
    id: 'intern_11',
    name: 'Tazkya Mutia Ramadhan',
    email: 'tazkya11@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607012400128',
    startup: initialStartups[1].name,
    status: 'active'
  },
  {
    id: 'intern_12',
    name: 'Alya Permata Nur Fajri',
    email: 'alya12@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607012430005',
    startup: initialStartups[2].name,
    status: 'active'
  },
  {
    id: 'intern_13',
    name: 'Muhammad Bagus Burhan',
    email: 'muhammad13@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607012430010',
    startup: initialStartups[3].name,
    status: 'active'
  },
  {
    id: 'intern_14',
    name: 'Andi Bayu Hanggoro',
    email: 'andi14@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607012400019',
    startup: initialStartups[4].name,
    status: 'active'
  },
  {
    id: 'intern_15',
    name: 'Zulfahmi',
    email: 'zulfahmi15@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607012400053',
    startup: initialStartups[0].name,
    status: 'active'
  },
  {
    id: 'intern_16',
    name: 'Rizky Nurdiansyah',
    email: 'rizky16@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607012400064',
    startup: initialStartups[1].name,
    status: 'active'
  },
  {
    id: 'intern_17',
    name: 'Vemas Seftaesa Dwi Setiawan',
    email: 'vemas17@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607012400076',
    startup: initialStartups[2].name,
    status: 'active'
  },
  {
    id: 'intern_18',
    name: 'Fahreza Azhar Ramadhan',
    email: 'fahreza18@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607012400060',
    startup: initialStartups[3].name,
    status: 'active'
  },
  {
    id: 'intern_19',
    name: 'Nanda Candikia',
    email: 'nanda19@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607012430009',
    startup: initialStartups[4].name,
    status: 'active'
  },
  {
    id: 'intern_20',
    name: 'Anak Agung Rizky Jhotama',
    email: 'anak20@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607012400131',
    startup: initialStartups[0].name,
    status: 'active'
  },
  {
    id: 'intern_21',
    name: 'Zahara',
    email: 'zahara21@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607012400136',
    startup: initialStartups[1].name,
    status: 'active'
  },
  {
    id: 'intern_22',
    name: 'Rafi Khairan Putra',
    email: 'rafi22@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607012400123',
    startup: initialStartups[2].name,
    status: 'active'
  },
  {
    id: 'intern_23',
    name: 'M. Dandy Alfariji',
    email: 'm.23@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607012400092',
    startup: initialStartups[3].name,
    status: 'active'
  },
  {
    id: 'intern_24',
    name: 'Cantika anggi anggraheni',
    email: 'cantika24@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607012400106',
    startup: initialStartups[4].name,
    status: 'active'
  },
  {
    id: 'intern_25',
    name: 'Naura Ramadhani',
    email: 'naura25@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607012430011',
    startup: initialStartups[0].name,
    status: 'active'
  },
  {
    id: 'intern_26',
    name: 'Amadea Salsabila',
    email: 'amadea26@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607012400063',
    startup: initialStartups[1].name,
    status: 'active'
  },
  {
    id: 'intern_27',
    name: 'April Adzania',
    email: 'april27@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607012400100',
    startup: initialStartups[2].name,
    status: 'active'
  },
  {
    id: 'intern_28',
    name: 'Siti Amany Fakhirah Riby',
    email: 'siti28@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607012400008',
    startup: initialStartups[3].name,
    status: 'active'
  },
  {
    id: 'intern_29',
    name: 'Nadine Nathania Pelleng',
    email: 'nadine29@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607012400125',
    startup: initialStartups[4].name,
    status: 'active'
  },
  {
    id: 'intern_30',
    name: 'Dian Tri Sari Daeli',
    email: 'dian30@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607012430001',
    startup: initialStartups[0].name,
    status: 'active'
  },
  {
    id: 'intern_31',
    name: 'Muhammad Taqi Izdihar',
    email: 'muhammad31@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607012430006',
    startup: initialStartups[1].name,
    status: 'active'
  },
  {
    id: 'intern_32',
    name: 'Johanes Darren Yehuda',
    email: 'johanes32@gmail.com',
    password: 'pesertamagang@26',
    role: 'intern',
    score: 0,
    attendanceCount: 0,
    presentCount: 0,
    permissionCount: 0,
    alpaCount: 0,
    sickCount: 0,
    totalDays: 20,
    nim: '607012400035',
    startup: initialStartups[2].name,
    status: 'active'
  },
];

export const initialActivities: ActivityLog[] = [];

export const initialReports: BehaviorReport[] = [];
